# Generated by Django 5.0.6 on 2024-07-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_alter_product_category_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
